name: test

on:
  push:
    branches:
      - 'main'
      - 'releases/v*'
  pull_request:
    branches:
      - 'main'
      - 'releases/v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Validate
        uses: docker/bake-action@v2
        with:
          targets: validate
      -
        name: Test
        uses: docker/bake-action@v2
        with:
          targets: test
      -
        name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/clover.xml
